"""Product import surface for the versioned shared MS core."""

from flame_ms_core.detector import (
    DETECTOR_VERSION,
    BOUNDARY_RULE,
    BIN_SIZE_MIN,
    BROAD_PEAK_WIDTH_SEC,
    LOW_TIC_THRESHOLD,
    LOW_ARRAY_LENGTH_THRESHOLD,
    LOW_ARRAY_LENGTH_SEVERE,
    PRIMARY_FALLBACK_HEIGHT_FRACTION,
    PRIMARY_FALLBACK_PROMINENCE_FRACTION,
    EVENT_COLUMNS,
    _INTEGER_EVENT_COLUMNS,
    _BOOLEAN_EVENT_COLUMNS,
    _STRING_EVENT_COLUMNS,
    DetectionResult,
    _typed_events,
    _validate_scan,
    _median_scan_step_sec,
    strict_contiguous_runs,
    build_bin_summary,
    select_quiet_platform,
    estimate_parameters,
    call_peak_indices,
    _as_float,
    _as_int,
    _local_scan_interval_sec,
    build_event_table,
    detect_events,
)
